### ISSUE TITLE
Need SMTP support

### ISSUE THREAD

**Issue by KMKoushik** [unsend-dev/unsend#46]
As most project use SMTP so they can switch providers easily, unsend also needs one. 

the way i see it is it will be a seperate node js service that act as smtp proxy and and calls the unsend api after parsing the email.

can use this as custom SMTP server: https://nodemailer.com/extras/smtp-server/

should be under `apps/smtp-server`

**Comment by harshsbhat** [comment]
Can you assign me this?

**Comment by KMKoushik** [comment]
thank you for working on this!
