### ISSUE TITLE
docs: Repeated description for both API and NodeJS

### ISSUE THREAD

**Issue by harshsbhat** [unsend-dev/unsend#66]
![image](https://github.com/user-attachments/assets/b2a8c9ab-2027-4ddc-965a-a4d927bdaaee)
 There should be a proper descriptive description for the NodeJS card.

**Comment by aditya-supare** [comment]
on it !

**Comment by KMKoushik** [comment]
@aditya-supare are you working on this?

**Comment by aditya-supare** [comment]
@KMKoushik  done

**Comment by KMKoushik** [comment]
@aditya-supare TYSM
